### ISSUE TITLE
Notifying the Spotify devs about this library

### ISSUE THREAD

**Issue by marioortizmanero** [ramsayleung/rspotify#101]
I couldn't find this library in [Spotify's page with the available Web API Libraries](https://developer.spotify.com/documentation/web-api/libraries/), so I figured it'd be useful to let them know to get a few more users. Here's an example of how it went for a similar library to which I contributed a bit: https://github.com/spotify/web-api/issues/1429

Opened an issue at https://github.com/spotify/web-api/issues/1595, @ramsayleung could you leave a comment in there as the developer of this library? Thanks!

**Comment by ramsayleung** [comment]
> so I figured it'd be useful to let them know to get a few more users

Actually, when I published this library, I once open an issue to notify the Spotify developers, but it seems no more response after that: https://github.com/spotify/web-api/issues/795

> could you leave a comment in there as the developer of this library? Thanks!

Of course, thanks for notifying the Spotify developers about this library

**Comment by marioortizmanero** [comment]
> Actually, when I published this library, I once open an issue to notify the Spotify developers, but it seems no more response after that: spotify/web-api#795

Ah, completely forgot to check if you had already done that. Let's just ping them again and see if it works, they have tons of stale issues :)

**Comment by ramsayleung** [comment]
> Ah, completely forgot to check if you had already done that
Never mind

> Let's just ping them again and see if it works, they have tons of stale issues

Yep, we can keep pinging them in your new issue, and your description of this crate is much more exciting and decent than mine.

**Comment by merisbahti** [comment]
this should be fixed now ❤️

**Comment by marioortizmanero** [comment]
Ah awesome! Thanks for letting us know, closing this
