### ISSUE TITLE
Adding undocumented endpoint "made for x"

### ISSUE THREAD

**Issue by mtshrmn** [ramsayleung/rspotify#104]
First of all, thank you for your great work.

I've noticed that both you and the spotify web api don't have the "made for x" endpoint. 
After digging in the original github web-api repository, I've found this [issue](https://github.com/spotify/web-api/issues/1192).

Do you plan on implementing it?

**Comment by ramsayleung** [comment]
Yep, I am going to implement this endpoint, right after adding the documentation of this endpoint. If there is no documentation for it, I have no idea about this endpoint's parameters and return values, have no way to implement it :)

PS, PR is welcome.

**Comment by mtshrmn** [comment]
Understandable. I'll try to implement it myself

**Comment by marioortizmanero** [comment]
This issue seems stale and there haven't been any updates for the `made for x` endpoint, so closing for now.
