### ISSUE TITLE
Environmental variables should have the prefix `SPOTIFY_`

### ISSUE THREAD

**Issue by marioortizmanero** [ramsayleung/rspotify#118]
The environmental variable names currently are `CLIENT_ID`, `CLIENT_SECRET` and `REFRESH_TOKEN`. I think it would be a better idea to use these same names with the prefix `SPOTIFY_` to avoid name collisions with other programs/libraries that use OAuth2, like `SPOTIFY_CLIENT_ID`.

By the way, I'll leave for 3-4 days so I won't be able to respond to issues/PRs.

**Comment by ramsayleung** [comment]
> I think it would be a better idea to use these same names with the prefix SPOTIFY_ to avoid name collisions with other programs/libraries that use OAuth2, like SPOTIFY_CLIENT_ID.

I think it will be better to have the prefix `RSPOTIFY_` just avoid name collisions with other Spotify libraries.

**Comment by marioortizmanero** [comment]
That's not a bad idea either. I think collisions with other Spotify libraries aren't that bad because you can share the credentials, but I'd rather keep it trouble-free with RSPOTIFY-
