### ISSUE TITLE
Introduce automatic token retrieval

### ISSUE THREAD

**Issue by hypixus** [ramsayleung/rspotify#130]
This is a feature request.

This project works perfectly, but as I'm trying to create application where user interacts only with generated GUI, i'm in no way capable of providing the URL user is redirected to after allowing application to use their data - because command line is off the limits, and this is hardcoded into the library ("Enter the URL you were redirected to: ")

A very simple solution would be implementing http server going with localhost:<someport>, where user is redirected to and application is just reading the data off the request directly (just like in [Listing 20-2 on rust cookbook](https://doc.rust-lang.org/book/ch20-01-single-threaded.html)).

If this is already implemented/has a possible workaround without rebuilding entire library, please let me know - I'll close the issue immediately.

**Comment by marioortizmanero** [comment]
This was being discussed at #4. I don't think that implementing a server is something this library should do, that's part of the user's implementation. The `examples/webapp` example covers this more or less, so you might want to take a look.

**Comment by hypixus** [comment]
I understand what you mean, yet having this hardcoded leaves user in need of rebuilding entire library to suit his needs - which is what i tried to avoid at first. Having limited rust knowledge leaves me with little to none understanding of example provided, but seeing its a matter of replacing a few lines and compiling thing on my own it sounds simple enough to do on my own. Thanks for your time, closing.

**Comment by marioortizmanero** [comment]
What is hardcoded? You can still get access tokens without the stdin method. `get_token` is just an utility for the CLI apps: https://github.com/ramsayleung/rspotify/blob/v0.9/src/util.rs#L94. This is going to be refactored for the next release but the concept will be the same. I strongly recommend you to learn enough Rust to understand the example I linked you, as it's basically the same thing as what you want.

**Comment by hypixus** [comment]
> get_token is just an utility for the CLI apps
That's what my understanding lacked. Having spent last hour on understanding line by line, I understand now that it can be used without changing library at all. Thanks once more!

**Comment by marioortizmanero** [comment]
I will confess the documentation leaves to be desired. Hopefully the next release will improve that :)
