### ISSUE TITLE
Update derive_builder

### ISSUE THREAD

**Issue by Plecra** [ramsayleung/rspotify#131]
This dependency draws in pre-1.0 versions of `proc_macro2` and `syn`, which will be duplicated in most codebases. `derive_builder` 0.8 updated to use the 1.0 versions of `proc_macro` and `syn`, which would improve the build times of most crates that depend on `rspotify`

**Comment by ramsayleung** [comment]
We are working on refactoring `rspotify` and `derive_builder` has been updated to `0.9`: https://github.com/ramsayleung/rspotify/blob/32dff3aa7d1a3d69169c0fb6f0670c75027e1399/Cargo.toml#L19
