### ISSUE TITLE
Consider making the cache file a feature 

### ISSUE THREAD

**Issue by marioortizmanero** [ramsayleung/rspotify#135]
The cache file feature is something I'm not sure how I feel about. While it's definitely useful, I'm not sure if it should be the default behaviour. It could be moved into a feature, which when activated, would use the cache file anywhere possible. Or instead of having `do_something` and `do_something_without_cache`, it could be `do_something` and `do_something_with_cache`.

What do you think? I need some opinions on this. I don't actually plan on changing anything but I want to propose any breaking changes before the next release.

**Comment by ramsayleung** [comment]
Yes, I think it's more proper to have a switch to control how does it work. My original thought was using `cache_path` as a trigger, as what I commented in #129:

```rust
    #[builder(default = "PathBuf::from(\".spotify_token_cache.json\")")]
    pub cache_path: PathBuf,
	// I am thinking about whether it's better to make cache_path optional, so we can decide to whether save the token into file or not by checking if cache_path exists, so we can remove function get_token_without_cache
``` 
Now, probably it's more suitable to make it as a feature, switching on compile time instead of runtime, as what you suggests.

**Comment by ramsayleung** [comment]
Any other proposals? I am gonna to start to work on this feature on this weekend as what @marioortizmanero suggests, makes cache file as a new feature.

**Comment by marioortizmanero** [comment]
Can you cross off more things from the meta issue before this? I would wait a bit more before this, let's see if anyone opposes this.

**Comment by ramsayleung** [comment]
Sure! We could leave this issue alone for a while.

**Comment by marioortizmanero** [comment]
This has been inactive for a while and noone has left their opinion so I would say we can introduce the `cache-file` feature. Should it be activated by default?

Also, do you still want to work on it @ramsayleung?

**Comment by ramsayleung** [comment]
> Should it be activated by default?

I think it would be good to active this feature by default, just makes `rspotify` work as before.

> Also, do you still want to work on it @ramsayleung?

Not yet, I am working on this issue: https://github.com/ramsayleung/rspotify/issues/163, I would like to work on this feature after merging the PR of #163, and we could say we have crossed off most of TODO items in #127
