### ISSUE TITLE
Cleanup of branches

### ISSUE THREAD

**Issue by marioortizmanero** [ramsayleung/rspotify#136]
Hey @ramsayleung, are there any branches you don't want removed? We could do a bit of a cleanup, since there are lots of unused ones: https://github.com/ramsayleung/rspotify/branches

**Comment by ramsayleung** [comment]
Great idea, those branches are left after merging, without deleting directly. I can cleanup those manually.

**Comment by marioortizmanero** [comment]
Thanks! Closing this
