### ISSUE TITLE
Authorization Code Flow with Proof Key for Code Exchange (PKCE) is missing

### ISSUE THREAD

**Issue by martinmake** [ramsayleung/rspotify#150]
It is a very exciting *Authorization Flow* for developers of server-less applications that use *Spotify API* directly.

Not only will the users of these applications no longer have to setup their own *Spotify Applications*,
but also the creators will get to see usage metrics of their applications in their *Spotify Dashboard*.

You can find out how it works [here](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow-with-proof-key-for-code-exchange-pkce) and [here](https://docs.rs/oauth2/3.0.0/oauth2/#getting-started-authorization-code-grant-w-pkce).

**Comment by ramsayleung** [comment]
Yes, `rspotify` doesn't support PKCE now, and it seems you are going to contribute it to `rspotify` #151 . Before you start to work, would you like to illustrate your though firstly? just like what @marioortizmanero did before, it's his proposal:

+ https://github.com/ramsayleung/rspotify/issues/112
+ https://github.com/ramsayleung/rspotify/pull/120
+ https://github.com/ramsayleung/rspotify/pull/129

The template of your proposal could be:

+ What are you going to build ?
+ Why would you like to build it?
+ How to implement your proposal?

As for how to implement your idea, now there are different ways to approach your idea, just to brainstorm the working solutions as much as possible, and try to clarify their pros and cons, then choose the best one(from where you stand). for example:

+ Solution A: 
  - pros: xx
  - cons: xx
+ Solution B: xxx
+ Solution C: xxx

You could take a look at this issue #134, it makes a great example.

And then inviting other developers to review your proposal :)
