### ISSUE TITLE
Implement new playlist endpoints

### ISSUE THREAD

**Issue by andrzejressel** [ramsayleung/rspotify#16]
Few months ago Spotify added changes to playlists: https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/.

To implement

- [x] GET /v1/playlists/{playlist_id}/tracks
- [x] POST /v1/playlists/{playlist_id}/tracks
- [x] PATCH /v1/playlists/{playlist_id}/tracks
- [x] PUT /v1/playlists/{playlist_id}/tracks
- [x] DELETE /v1/playlists/{playlist_id}/tracks

- [x] ~~GET /v1/playlists/{playlist_id} ([PR](https://github.com/samrayleung/rspotify/pull/15))~~
- [x] PUT /v1/playlists/{playlist_id}

- [x] POST /v1/me/playlists

- [ ] GET /v1/playlists/{playlist_id}/images
- [ ] PUT /v1/playlists/{playlist_id}/images

**Comment by marioortizmanero** [comment]
Only the image endpoints are left, so I'm creating a new issue with more details
