### ISSUE TITLE
Example links in docs.rs are broken

### ISSUE THREAD

**Issue by manojkarthick** [ramsayleung/rspotify#168]
**Describe the bug**
The links to examples are broken in the crate documentation page.

**To Reproduce**
1. Go to https://docs.rs/crate/rspotify/0.10.0
2. Scroll down to 'Examples' section
3. Click on any of the links present under the section, all of them seem to be broken.

**Expected behavior**
Should link to source code of the examples.

**Log/Output data**
N/A

**Additional context**
I can see that the examples are present in the crate's source code at https://docs.rs/crate/rspotify/0.10.0/source/examples/

**Comment by marioortizmanero** [comment]
Closing as this is resolved in the master branch.
