### ISSUE TITLE
Error parsing token_info 

### ISSUE THREAD

**Issue by rstcologne** [ramsayleung/rspotify#205]
**Describe the bug**
I'm trying to run one of the very simple example programs providing my own clilent_id and secret (not pasted here, replaced below with my_client_id and my_secret_key). 

```
extern crate rspotify;

use rspotify::client::Spotify;
use rspotify::oauth2::SpotifyClientCredentials;
use rspotify::senum::Country;

#[tokio::main]
async fn main() {
    // Set client_id and client_secret in .env file or
    // export CLIENT_ID="your client_id"
    // export CLIENT_SECRET="secret"
    //let client_credential = SpotifyClientCredentials::default().build();


    // Or set client_id and client_secret explictly
    let client_credential = SpotifyClientCredentials::default()
         .client_id("my_client_id")
         .client_secret("my_secret_key")
         .build();
    let spotify = Spotify::default()
        .client_credentials_manager(client_credential)
        .build();
    let birdy_uri = "spotify:artist:2WX2uTcsvV5OnS0inACecP";

    let tracks = spotify
        .artist_top_tracks(birdy_uri, Country::UnitedStates)
        .await;
    
    println!("{:?}", tracks.unwrap());
}

```

**To Reproduce**
compile and run

**Expected behavior**
println! at the end sending output to the console

**Log/Output data**
thread 'main' panicked at 'Error parsing token_info response: reqwest::Error { kind: Decode, source: Error("missing field `scope`", line: 1, column: 142) }', /home/rst/.cargo/registry/src/github.com-1ecc6299db9ec823/rspotify-0.10.0/src/oauth2.rs:475:14

**Additional context**
Please bear with me, I'm learning rust, so I might be doing something wrong here but I figured, I'd get at least and example program to run :-)

**Comment by ramsayleung** [comment]
It seems there is something wrong your cache token, would you like to post it here. The default cache token would be `/your-project-path/.spotify_token_cache.json`.

**Comment by amPerl** [comment]
Also seeing this as I'm converting an old python project over to `rspotify`. I don't think `TokenInfo` always returns a `scope`, specifically when there are none requested for fetching non-user data like the issue author is.

**Comment by ramsayleung** [comment]
@rstcologne As amPerl pointed out, you could give the `master` branch for a try, since we have been working on it for months to make it easier to use.

**Comment by marioortizmanero** [comment]
Closing as this has already been fixed.
