### ISSUE TITLE
[meta] could you tag crate releases

### ISSUE THREAD

**Issue by hhirtz** [ramsayleung/rspotify#210]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to find the commit from which `cargo publish` was called and I find out there's no tag for it. ':-)

**Describe the solution you'd like**
Can you please `git tag v0.x.x && git push origin v0.x.x` when you publish a version.

**Describe alternatives you've considered**
No need to make a GitHub release, just a tag would work.

**Additional context**
https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by ramsayleung** [comment]
Great point, thanks for your heads-up, I will tag the crate release when I release a new version in the future. It's my bad to forget to do so before :-)

**Comment by marioortizmanero** [comment]
we should create a continuous deployment flow for github CI that automatically uploads everything to crates.io once a tag is published

**Comment by ramsayleung** [comment]
> we should create a continuous deployment flow for github CI that automatically uploads everything to crates.io once a tag is published

I have pushed a PR to do so.
