### ISSUE TITLE
`TrackId` in `FullTrack` can be null

### ISSUE THREAD

**Issue by aome510** [ramsayleung/rspotify#279]
**Describe the bug**
According the specs defined in [docs.rs](https://docs.rs/rspotify-model/0.11.2/rspotify_model/track/struct.FullTrack.html), `TrackId` in `FullTrack` is not null. However, [get playlist items](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-playlists-tracks) can return a track object will null id.

**To Reproduce**
1. To get the playlist having a track with null ID, run
```
curl -X "GET" \
"https://api.spotify.com/v1/playlists/2RI4NLi6npcHfCNQQxP3nM/tracks?limit=100&offset=900" \
-H "Accept: application/json" -H "Content-Type: application/json" \
-H "Authorization: Bearer <TOKEN>" \
> /tmp/data.txt
```
2. Then run `jq .items[].track.id /tmp/data.txt` to view the list of track's ids

**Expected behavior**
There should be at least one null entry

**Comment by marioortizmanero** [comment]
Oh nice, the docs have been updated and look a bit more detailed now. Which means that the links are broken... I've opened #281 for that.

I was able to reproduce your issue with your indications, which should be fixed with #282

Thanks for the report!
