### ISSUE TITLE
"from_token" is currently not a valid parameter

### ISSUE THREAD

**Issue by hrkfdn** [ramsayleung/rspotify#28]
Hey,

thanks for your work on the library. I'm currently trying to search for tracks using rspotify. According to the documentation, `from_token` can be passed as a `market` parameter to search in the market tied to the token.

However, the `search_*` functions seem to require an Option<Country> parameter. There seems to be no Country enum representing `from_token`, unless I am missing something?

**Comment by hrkfdn** [comment]
Mhh, or is passing `None` equivalent to `from_token`?

**Comment by samrayleung** [comment]
Could you show which `search_*` function you are using to search for tracks, I am not sure which `from_token` you are talking about ?

**Comment by hrkfdn** [comment]
For instance, `search_track` (https://github.com/samrayleung/rspotify/blob/master/src/spotify/client.rs#L420):
The documentation states the following for market:
`market - An ISO 3166-1 alpha-2 country code or the string from_token.`

Maybe I misread it? The way I interpreted it, is that `market` either gets an alpha-2 country code or the literal "from_token", but in the signature the type is declared as `Option<Country>`. So for me, it was unclear how to set the parameter to derive the market from the token.

**Comment by Qluxzz** [comment]
What would be the best course of action if we want to enable using the user tokens country instead of having to supply a country ourselves?

A solution would be a type of Country | FromToken using an enum maybe?
```Rust
enum Market {
    Country(Country),
    FromToken
}
```
And then using it like this?
```Rust
if let Some(market) = market {
    params.insert("country".to_owned(), match market {
        Market::Country(c) => c.to_string(),
        Market::FromToken => "from_token".to_string()
    });
}
```

As @hrkfdn mentioned, country defaults to US if no country was supplied and country is required, would not "from_token" be a better default here?

**Comment by Qluxzz** [comment]
Any thoughts on this? I'm willing to implement this myself and send a PR but I would need to know which way you would prefer.

**Comment by marioortizmanero** [comment]
Sorry about that. Yes, I think that's the best solution to keep it type-safe. Go ahead and make a PR if you want :)

The API doesn't specify a default value so I'm not sure what you're referring to with __defaulting to US__. If anything I would just not send that parameter.

**Comment by Qluxzz** [comment]
> The API doesn't specify a default value so I'm not sure what you're referring to with _defaulting to US_. If anything I would just not send that parameter.

Sorry, seems like it was only one function that defaulted it to the US while it is optional everywhere else.

https://github.com/ramsayleung/rspotify/blob/18f2396026b598edb9c54616ac82ea62715f3f06/src/client.rs#L329-L332

I feel like defaulting to "from_token" is the better option here.

**Comment by marioortizmanero** [comment]
Yes, I would consider that code snippet wrong; it shouldn't default to the US.

In that case it is a required field, so I just wouldn't use an `Option` at all. Why not just keep it as close as possible to the real API?
