### ISSUE TITLE
Doc links are broken again

### ISSUE THREAD

**Issue by marioortizmanero** [ramsayleung/rspotify#281]
**Describe the bug**
Looks like the spotify team revamped their reference page: https://developer.spotify.com/documentation/web-api/reference/#/

Which means that their reference links are completely broken now.

**To Reproduce**
1. Go to https://docs.rs/rspotify/0.11.2/rspotify/clients/base/trait.BaseClient.html#method.artist
2. Click on `reference`
3. See that it's broken

**Comment by marioortizmanero** [comment]
Not sure how to tackle this for `rspotify-model`, it seems that said section has been removed...

**Comment by ramsayleung** [comment]
To be honest, I think the upstream(Spotify API) is pretty unstable, perhaps we should figure out a better way to maintain the `field` information of the structure

**Comment by marioortizmanero** [comment]
That sounds complicated though... I don't think they'll change it for a long time now, it's pretty much got everything already. I hope...

**Comment by marioortizmanero** [comment]
I guess we could just remove the reference links in the `rspotify-model` crate? The endpoints already have links with their models anyway.

The other option would be to add links to whichever endpoint uses that specific model. For example, for `SimplifiedAlbum` it could point to https://developer.spotify.com/documentation/web-api/reference/#/operations/get-an-artists-albums. But I don't really have time right now to do that for every model, and it might be an unnecessary maintainaince cost, since other spotify libraries don't even have [links to the reference](https://tekore.readthedocs.io/en/stable/reference/models.html#tekore.model.FullArtist).

**Comment by ramsayleung** [comment]
> I guess we could just remove the reference links in the rspotify-model crate? The endpoints already have links with their models anyway.

I agree with this solution, the other solution is expensive.

**Comment by marioortizmanero** [comment]
Alright! I'll write a PR for that and then we can release a new version.
