### ISSUE TITLE
push 0.11.5

### ISSUE THREAD

**Issue by wael444** [ramsayleung/rspotify#307]
https://github.com/Rigellute/spotify-tui/issues/960

this makes [spotify-tui](https://github.com/Rigellute/spotify-tui) completely useless. will be useful when 0.11.5 is pushed.

**Comment by marioortizmanero** [comment]
I think only @ramsayleung is able to release new versions, since I don't own the package?

**Comment by ramsayleung** [comment]
@marioortizmanero Mario, I have sent an owner invitation to you, would you like become an owner of `rspotify` and help me maintain this project, it's a pleasure to work with you :)

<img width="1796" alt="image" src="https://user-images.githubusercontent.com/14180681/160312872-27674f7f-eaa5-4d18-8abd-65d50164a1b8.png">

>  this makes [spotify-tui](https://github.com/Rigellute/spotify-tui) completely useless. will be useful when 0.11.5 is pushed.

As for this, I would like to create an PR to upgrade to v0.11.5

**Comment by marioortizmanero** [comment]
Alright thanks a bunch! Same goes to you, awesome maintainer :)
