### ISSUE TITLE
Missing git tag for 0.10

### ISSUE THREAD

**Issue by The-Compiler** [ramsayleung/rspotify#311]
It looks like this repository [has no tag at all](https://github.com/ramsayleung/rspotify/tags) for the 0.10 release. I suppose 33d8f770b3d0bcaaccd0c83c0ab0481edb7e5eaa or so should be tagged accordingly?

**Comment by marioortizmanero** [comment]
Yeah, the tags are a bit messy. For some reason, [we have both `11.5` and `11.5.0`](https://github.com/ramsayleung/rspotify/tags). Similarly, v0.11.5.1 was released in October 2020, apparently??

Let me know if [this new tag](https://github.com/ramsayleung/rspotify/releases/tag/v0.10.0) is what you wanted.
