### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by Bunch-of-cells** [ramsayleung/rspotify#314]
**Examples don't work in the latest release**
Examples in the examples folder are not up to date with the latest release. The first example (example/ureq/device.rs) itself is not working, how are new people supposed to use this lib? There is not much documentation in the docs either on how to get started.

**Comment by marioortizmanero** [comment]
Being a bit friendlier when opening issues like this helps getting it solved earlier. And you need to add more details; you ignored the template we have for bug reports (maybe templates don't work with your app?): what exactly went wrong, what did you try, etc. It wasn't too bad, but you know, we're volunteers after all :)

Also, not sure what exactly is wrong?

```
$ cargo r --example device --features=env-file,cli,client-ureq,ureq-rustls-tls --no-default-features
Opened https://accounts.spotify.com/authorize?scope=user-read-playback-state&response_type=code&client_id=e1dce60f1e274e20861ce5d96142a4d3&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fcallback&state=cZMNhhjhSA0dUYJK in your browser.
Please enter the URL you were redirected to:
http://localhost:8000/callback?code=AQDKg3HVeCqqqfestfRv36ip9cEf67xlgdf9QHVMUOmoVl7TquUgB5W8XqUxmPRNfZVGPLAeGRz7dbBaZXOmoG1S2z9qx3pcOw_Efp4eXxSZuDiTpQf0hUpwINXy8hpzq5V_0A4C_2JoJCMYPXaieM1wthsGjdEV4wtoLvr7q6L2O4JEK7-DkRqHQNpcdg7zQ6fJLz6NS9dtIPDG&state=cZMNhhjhSA0dUYJK
Request: Ok([Device { id: Some("3b9d3644f5ba85f11e92cd279623a229e6d0e448"), is_active: false, is_private_session: false, is_restricted: false, name: "btwiusedell", _type: Computer, volume_percent: Some(100) }])
```

Finally, we have a section for those [getting started, check it out here](https://docs.rs/rspotify/0.11.5/rspotify/#getting-started). We accept criticism and suggestion, but of course, you need to tell us exactly what is wrong.

**Comment by marioortizmanero** [comment]
Being a bit friendlier when opening issues like this helps getting it solved earlier. And you need to add more details; you ignored the template we have for bug reports (maybe templates don't work with your app?): what exactly went wrong, what did you try, etc. It wasn't too bad, but you know, we're volunteers after all :)

Also, not sure what exactly is wrong?

```
$ cargo r --example device --features=env-file,cli,client-ureq,ureq-rustls-tls --no-default-features
Opened https://accounts.spotify.com/authorize?scope=user-read-playback-state&response_type=code&client_id=e1dce60f1e274e20861ce5d96142a4d3&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fcallback&state=cZMNhhjhSA0dUYJK in your browser.
Please enter the URL you were redirected to:
http://localhost:8000/callback?code=abc&state=abc
Request: Ok([Device { id: Some("3b9d3644f5ba85f11e92cd279623a229e6d0e448"), is_active: false, is_private_session: false, is_restricted: false, name: "btwiusedell", _type: Computer, volume_percent: Some(100) }])
```

Finally, we have a section for those [getting started, check it out here](https://docs.rs/rspotify/0.11.5/rspotify/#getting-started). We accept criticism and suggestions, but of course, you need to tell us exactly what is wrong.
