### ISSUE TITLE
Make Spotify base URLs configurable for tests

### ISSUE THREAD

**Issue by jjmark15** [ramsayleung/rspotify#350]
**Is your feature request related to a problem? Please describe.**
I want to be able to write tests against a local mock of Spotify. Spotify URLs are hard-coded in the library which makes this impractical.

e.g. https://github.com/ramsayleung/rspotify/blob/9197a908e9a61e20b47e22cac6cf9af75c6769b4/src/lib.rs#L188

**Describe the solution you'd like**
Make target base URLs configurable.

**Comment by marioortizmanero** [comment]
I saw `aspotify` did something like that but I always wondered why it would be useful. So you've replicated the API? Would you be able to tell me more about it?

**Comment by jjmark15** [comment]
Sure 👍🏻 . I generally prefer black-box functional (or integration depending on terminology) testing of an API. In order to do that I need to be able to make a real HTTP call to a downstream, which usually means using an http mock. Not sure if I've explained myself well enough there 😓

**Comment by marioortizmanero** [comment]
I was wondering whether we should have these fields as a `String` or as a `&'static str`. It's not like anyone is going to modify the prefix URL at runtime, right?
