### ISSUE TITLE
Progress time received from API can be negative

### ISSUE THREAD

**Issue by bamode** [ramsayleung/rspotify#363]
**Describe the bug**
This issue effects specifically the structs `CurrentlyPlayingContext` and `CurrentPlaybackContext` when deserializing the Spotify API response that corresponds to the `progress` field of these structs. It appears to be parsing it as a `u32` to turn into a `std::time::Duration` and this part of the API response is occasionally a negative number. This results in upstream bugs in the spotifyd and spotify-tui projects.

**Expected behavior**
The API deserialization should be able to replace an unexpected negative time value with some default.

**Comment by ramsayleung** [comment]
Thanks for your report, The Spotify's documentation doesn't point out the `progress` could be a negative number.

 If `progress` could be a negative number, then parsing it as an `u32` to turn into a `std::time::Duration` is inappropriate. `std::time::Duration` doesn't support negative value.

I would like to replace `std::time::Duration` to `chrono::Duration`, which supports negative value. It would be  a break change.

**Comment by ramsayleung** [comment]
If we consider replacing `std::time::Duration` to `chrono::Duration`, we need to replace all [fields](https://github.com/ramsayleung/rspotify/search?l=Rust&q=Duration) using `std::time::Duration` to `chrono::Duration`. Otherwise, it will become inconsistent that some fields are using `std::time::Duration` to represent time, other fields are using `chrono::Duration` to represent time.

**Comment by marioortizmanero** [comment]
Do we know in which cases we receive a negative value? Another option is to have a custom serializer that sets these cases to zero, though I do prefer to represent the API as closely as possible with `chrono::Duration`.

**Comment by ramsayleung** [comment]
As @bamode points out, the `progress` field in `CurrentlyPlayingContext ` could be negative. I think it doesn't make sense if we set these cases to zero.
