### ISSUE TITLE
Allow usage with provided tokens

### ISSUE THREAD

**Issue by TPausL** [ramsayleung/rspotify#380]
**Is your feature request related to a problem? Please describe.**
I use authorization via [Ory](https://ory.sh) for my app and connect to spotify via them, so i already have authenticated the user. I can't figure out a way to insert that existing token into a rspotify client. I tried manuallly creating a Token from the library but can't access the correct duration and it is a not an intendet use I guess.

**Describe the solution you'd like**
It would be cool if you could use the api directly (just inserting the provided token to every request or on a per request basis) or create an auth flow from existing (external) data (tokens, expire date).

**Comment by ramsayleung** [comment]
> I can't figure out a way to insert that existing token into a rspotify client. I tried manuallly creating a Token from the library but can't access the correct duration and it is a not an intendet use I guess.

I am not familiar with `Ory`, what do you get after authenticating with user? 

Does this work for you?
```rs
let manual_token = Token {
    access_token: String::from("your-access-token"),
    expires_in: Duration::seconds(3600), // The time period for which your access token is valid.
    expires_at: Some(Utc::now() + Duration::seconds(3600)),
    refresh_token: None,
    scopes: scopes!("user-follow-read user-follow-modify your-scopes")
};
let spotify = AuthCodeSpotify:: from_token(manual_token);  
let user = spotify.me();
println!("Request: {user:?}");
```

**Comment by TPausL** [comment]
Yeah I tried that before. My problem was that the correct type for the date wasn't accessible but i figured it out now with using the defaults and then setting the my access token. In order to refresh these I now create an AuthCodeFlow and set that token manually later. Is there are more elegant way or is that fine?
