### ISSUE TITLE
Can't turn a Token to a serde_json::value::Value and back

### ISSUE THREAD

**Issue by PaulOlteanu** [ramsayleung/rspotify#392]
**Describe the bug**
Trying to create a `Token` from a `serde_json::value::Value` results in an error `invalid type string expected a borrowed string`.

**To Reproduce**
1. Create a `Token`/get a token from a client
2. Create a `Value` from this token (`let value = json!(token)`)
3. Turn the value back to a token (`let token = serde_json::from_value(value)`)

**Expected behavior**
A `Token` should be able to be created from a `Value`

**Additional context**
The issue seems to come from the deserialization portion of `space_separated_scopes`. Changing https://github.com/ramsayleung/rspotify/blob/6d304de632a84f79c35cb9ff4a0e66be238cf205/rspotify-model/src/custom_serde.rs#L225

to be

```let scopes: String = Deserialize::deserialize(d)?;```

fixes the issue, but I'm not familiar enough with how serde deserialization works to judge if this is a good solution

**Comment by ramsayleung** [comment]
I can reproduce this bug with this following test case:

```rust
    #[test]
    fn test_token_deserialize() {
        let mut scopes = HashSet::<String>::new();
        scopes.insert("user-read-email".to_owned());
        let tok = Token {
            access_token: "access_token".to_string(),
            scopes: scopes,
            ..Default::default()
        };
        let value = json!(tok);
        let token = serde_json::from_value::<Token>(value);
        assert!(token.is_ok());
        assert_eq!(token.unwrap().scopes, tok.scopes);
    }
```
I have created a PR to fix this problem.

**Comment by ramsayleung** [comment]
This problem has been fixed.
