### ISSUE TITLE
0.11.6 is a breaking change, patches should never be breaking changes

### ISSUE THREAD

**Issue by ForsakenHarmony** [ramsayleung/rspotify#395]
Running `cargo update` should never cause breaking changes

Please adhere to semver if you publish to [crates.io](https://crates.io/) (or well not necessarily semver, because that allows breaking on patch, rust does not)

**Comment by ForsakenHarmony** [comment]
alternatively, please publish `v1.0.0`

**Comment by blueforesticarus** [comment]
It is pre-1.0, so it is actually a minor revision bump.

**Comment by ForsakenHarmony** [comment]
strongly disagree as cargo, npm and others will update anything after the first non 0 in the version number without asking
