### ISSUE TITLE
Incorrect type for playlist position

### ISSUE THREAD

**Issue by hrkfdn** [ramsayleung/rspotify#407]
**Describe the bug**
With #375 some types were changed from integers to `chrono::Duration`. While this is a great change, I believe a mistake snuck in:

https://github.com/ramsayleung/rspotify/blob/0a6c136b56ab1e882e26ac536a44c405a37706e4/src/clients/oauth.rs#L292-L315

**Expected behavior**

The position in this method is a playlist position and not time related. I don't think `chrono::Duration` is appropriate here. What do you think?

**Comment by ramsayleung** [comment]
Agree, it should be an integer instead of `Duration`, because it's a zero-based index

**Comment by ramsayleung** [comment]
This problem has been fixed, the type of `position` rollback to `Option<u32>`
