### ISSUE TITLE
Missing market field on the album API call

### ISSUE THREAD

**Issue by rileyallyn** [ramsayleung/rspotify#423]
**Describe the bug**
The album function https://github.com/ramsayleung/rspotify/blob/08387401aace34b7e807a78d2f9be3cb48d94da4/src/clients/base.rs#L373 does not have a param for the market field which is in the API documentation.

**To Reproduce**
N/A

**Expected behavior**
Having a market field 

**Log/Output data**
N/A

**Additional context**
https://developer.spotify.com/documentation/web-api/reference/get-an-album and https://developer.spotify.com/documentation/web-api/concepts/track-relinking

**Comment by ramsayleung** [comment]
I think `Spotify` just updated their API by adding a new field named `market`, `RSpotify` should update the `album` endpoint accordingly.

So, feel free to create a PR to fix this problem.
