### ISSUE TITLE
Yank version 0.11.7 from crates.io

### ISSUE THREAD

**Issue by ThomasFrans** [ramsayleung/rspotify#425]
**Describe the bug**
There seemed to have been a breaking change in one of the playlist methods (use of duration instead of an integer) which made its way onto crates.io. Some people are experiencing issues when installing other programs using that version. I wonder whether it would make sense to yank it as that would prevent these issues. It would still allow crates that are already using it to keep using the yanked version, but would prevent further confusion.

**Expected behavior**
Minor version increases should not have breaking API changes. A new version could be published with a major version increase (which is recommended by the semantic versioning standard when there is an unexpected breaking change). I think the breaking change has already been resolved so this major version increase wouldn't be needed.

**Additional Context**
I hope it's OK to suggest this. It's not fun to yank a release, but since it can cause confusion and is already confusing some people when they use `cargo install` without adding `--locked`, it would make sense to prevent this. :slightly_smiling_face:

**Comment by ramsayleung** [comment]
Hi Thomas, thanks for your suggestion, I think your point makes sense and reasonable, this library introduces some breaking API changes, so it shouldn't be a minor version increase, and it also introduces a fatal problem with the playlist method, so the v0.11.7 should be yanked from crates.io.

But I think a better solution is releasing a new version like `v0.12` before yanking the v0.11.7 version, so other developers are able to upgrade to the latest version.

I would like to publish a new version after merging these two PRs:
+ https://github.com/ramsayleung/rspotify/pull/424
+ https://github.com/ramsayleung/rspotify/pull/418

**Comment by ramsayleung** [comment]
Closing this issue since the v0.11.7 has been yanked.
