### ISSUE TITLE
Incorrect url in OAuthClient documentation

### ISSUE THREAD

**Issue by Arya-LL** [ramsayleung/rspotify#450]
**Describe the bug**
The documentation for the OAuthClient trait has the wrong url for the reference link (line 960, file src/clients/oauth.rs)

**To Reproduce**
1. Go to 'fn current_playing under rspotify::clients::OAuthClient in rspotify's documentation'
2. Click on 'Reference'

**Expected behavior**
Expect to find https://developer.spotify.com/documentation/web-api/reference/get-the-users-currently-playing-track

**Log/Output data**
Redirected to https://developer.spotify.com/documentation/web-api/reference/get-recently-played

**Additional context**
I am new to GitHub and contributing to open-source projects, I apologize if I addressed the issue incorrectly. Thank you for the amazing project!

**Comment by ramsayleung** [comment]
This problem has been fixed in this [PR](https://github.com/ramsayleung/rspotify/pull/451) :)
