### ISSUE TITLE
Start playback at `position_ms`

### ISSUE THREAD

**Issue by Rigellute** [ramsayleung/rspotify#51]
Firstly, thank you for creating this amazing crate, it's made working with the spotify API so fun. 

I have this usecase 
> As a user, I should be able to toggle play/pause and resume playback at the previous position.

Looks like the spotify api let's you pass in `position_ms` to the `play` endpoint https://developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback/

Which I think is what I need?

#### Potential solution
Pass `position_ms` as a fourth paramter to the `start_playback` function.

Or perhaps I am missing something? Is there an existing way of resuming playback?

**Comment by ramsayleung** [comment]
No, you didn't do anything wrong or miss something, it's just my mistake. It seems when I develop this crate, Spotify doesn't provide such an argument, I will fix it later.

**Comment by ramsayleung** [comment]
And just feels free to make a PR to fix this issue, it's easy :)

**Comment by Rigellute** [comment]
Cool thanks. Have raised a PR adding this 👍
