### ISSUE TITLE
No way to create AuthCodePkceSpotify from token with config

### ISSUE THREAD

**Issue by gdesmott** [ramsayleung/rspotify#511]
There is currently no way to create `AuthCodePkceSpotify` with a custom config.

Is there any reason to not have `AuthCodePkceSpotify::from_token_with_config()` as there is for `AuthCodeSpotify`?

**Comment by gdesmott** [comment]
I think we need this to be able to refresh an expired cached token, see https://github.com/ramsayleung/rspotify/pull/512

**Comment by ramsayleung** [comment]
The `AuthCodePkceSpotify` implementation was contributed by another maintainer, so I don't have full context on the reasoning behind not including a `from_token_with_config()` method, my intuition is he might just miss the requirement of the function.
