### ISSUE TITLE
Using proxy

### ISSUE THREAD

**Issue by conilas** [ramsayleung/rspotify#59]
Hey there!

I tried to use spotify-tui (which apparently uses this library) inside my company, where everything runs behind a proxy. After a little digging, I noticed they were trying to get the json token for oauth (https://github.com/ramsayleung/rspotify/blob/master/src/spotify/oauth2.rs), but the client from reqwest is being built without the proxy. 

They have a good doc on it (https://docs.rs/reqwest/0.7.0/reqwest/struct.Proxy.html), so I was able to change the Client building line the proxy.

Question is: do you guys plan to have any take on that? I might be able to make a PR if that is not/not supposed to be in the roadmap or anything.

 Thanks!

**Comment by ramsayleung** [comment]
PR is certainly welcome, It frustrated that I don't have time to add proxy feature to rspotify now, hence it's great if you could contribute to it.

**Comment by ramsayleung** [comment]
I have updated `reqwest` to the latest version, now rspotify supports system proxy by default(Notes that `reqwest` system proxy doesn't support socks proxy for now, check [this issue](https://github.com/seanmonstar/reqwest/issues/790) for more details). For more details, please check this PR https://github.com/ramsayleung/rspotify/pull/70.
