### ISSUE TITLE
ETag

### ISSUE THREAD

**Issue by DomWilliams0** [ramsayleung/rspotify#6]
A feature that would be handy would be the support of ETags, as detailed in Spotify's docs:

> Conditional Requests
> 
> Most API responses contain appropriate cache-control headers set to assist in client-side caching:
> 
>  - If you have cached a response, do not request it again until the response has expired.
>  - If the response contains an ETag, set the If-None-Match request header to the ETag value.
>  - If the response has not changed, the Spotify service responds quickly with 304 Not Modified status, meaning that your cached version is still good and your application should use it.

I'm happy to work on this and submit a pull request, maybe as an optional --feature?

**Comment by samrayleung** [comment]
I do appreciate it if you are willing to work on this feature, because I don't have enough time to polish this library :)
