### ISSUE TITLE
Update Reqwest

### ISSUE THREAD

**Issue by daniel-tp** [ramsayleung/rspotify#67]
It looks like the issue behind #55 has been fixed in Reqwest 0.9.22 (https://github.com/seanmonstar/reqwest/issues/541#issuecomment-540207036)

Updating to this version (or newer) will also cause it to use Rustls 0.16, which fixes some dependency collision issues I have been having with this and serenity.

**Comment by ramsayleung** [comment]
I have updated `reqwest` to the latest version(0.10.1), everything should works well now?

**Comment by ramsayleung** [comment]
Close this issue for the participant hasn't responded for more information.
