### ISSUE TITLE
Issue when using corporate proxy

### ISSUE THREAD

**Issue by freijon** [ramsayleung/rspotify#83]
I'm using ncspot which uses rspotify, that's why I open the issue here. I'm facing an error when behind a proxy. I'm using the http_proxy, https_proxy env variables. From the logs I can see that other network tasks work in ncspot, like authentication and token handout, but rspotify fails to connect...

Since #59 is closed, I assume it's an unrealted issue...? But it seems that it has something to do with `reqwest` as well.

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: "https://api.spotify.com/v1/me/", source: hyper::Error(Connect, Os { code: 10054, kind: ConnectionReset, message: "An existing connection was forcibly closed by the remote host." }) }', src\libcore\result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:61
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src\libstd/panicking.rs:373
  12: rust_begin_unwind
             at src\libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src\libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src\libcore/result.rs:1165
  15: core::result::Result<T,E>::unwrap
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libcore/result.rs:933
  16: rspotify::spotify::client::Spotify::internal_call
             at C:\Users\jonas.frei\.cargo\registry\src\github.com-1ecc6299db9ec823\rspotify-0.8.0\src\spotify/client.rs:163
  17: rspotify::spotify::client::Spotify::get
             at C:\Users\jonas.frei\.cargo\registry\src\github.com-1ecc6299db9ec823\rspotify-0.8.0\src\spotify/client.rs:189
  18: rspotify::spotify::client::Spotify::me
             at C:\Users\jonas.frei\.cargo\registry\src\github.com-1ecc6299db9ec823\rspotify-0.8.0\src\spotify/client.rs:960
  19: rspotify::spotify::client::Spotify::current_user
             at C:\Users\jonas.frei\.cargo\registry\src\github.com-1ecc6299db9ec823\rspotify-0.8.0\src\spotify/client.rs:966

**Comment by ramsayleung** [comment]
@freijon Hi Jonas, would you like to submit more information on this issue: https://github.com/seanmonstar/reqwest/issues/823
the author of `reqwest` needs more information to address the problem.
