### ISSUE TITLE
specified package `rspotify v0.9.0` has no binaries

### ISSUE THREAD

**Issue by hosseind2** [ramsayleung/rspotify#86]
when I want install this package it says `specified package `rspotify v0.9.0` has no binaries`

**Comment by ramsayleung** [comment]
Could you add more description about this issue, I don't understand what your issue means :(

**Comment by hosseind2** [comment]
I just did run `cargo install rspotify`, but it fails, and gives this error
<img width="607" alt="Screen Shot 2020-03-23 at 7 19 21 PM" src="https://user-images.githubusercontent.com/57390535/77329152-351fdc80-6d3b-11ea-865a-ffa66a99aaf2.png">

**Comment by hosseind2** [comment]
I am using this boilerplate `https://github.com/uetchy/create-react-app-wasm` and I want use this package to create an spotify implementation by rust and wasm, but now I have this issue
when I put `rspotify = "0.9.0"` manually in Cargo.toml and hit npm start, it starts to download packages but I get this errors, this just happens when I want to use this package

<img width="1218" alt="Screen Shot 2020-03-23 at 9 16 39 PM" src="https://user-images.githubusercontent.com/57390535/77340914-98196f80-6d4b-11ea-93ca-9d8a14c8b80d.png">

**Comment by ramsayleung** [comment]
> I just did run `cargo install rspotify`, but it fails, and gives this error

Rspotify is not a binary package, it's a crate, you could not install rspotify with `cargo install rspotify` check this link for more detail: https://stackoverflow.com/questions/37706999/error-installing-a-crate-via-cargo-specified-package-has-no-binaries

**Comment by ramsayleung** [comment]
> I am using this boilerplate `https://github.com/uetchy/create-react-app-wasm` and I want use this package to create an spotify implementation by rust and wasm, but now I have this issue
> when I put `rspotify = "0.9.0"` manually in Cargo.toml and hit npm start, it starts to download packages but I get this errors, this just happens when I want to use this package
> 
> <img alt="Screen Shot 2020-03-23 at 9 16 39 PM" width="1218" src="https://user-images.githubusercontent.com/57390535/77340914-98196f80-6d4b-11ea-93ca-9d8a14c8b80d.png">

I think it's something related to `webbrowser`, which is the sub dependency of `rspotify`, the error message says `webbrowser` only supports Windows, Linux, Macos, BSD, it doesn't support your operating system, what kind of OS are you using ?

**Comment by hosseind2** [comment]
> > I am using this boilerplate `https://github.com/uetchy/create-react-app-wasm` and I want use this package to create an spotify implementation by rust and wasm, but now I have this issue
> > when I put `rspotify = "0.9.0"` manually in Cargo.toml and hit npm start, it starts to download packages but I get this errors, this just happens when I want to use this package
> > <img alt="Screen Shot 2020-03-23 at 9 16 39 PM" width="1218" src="https://user-images.githubusercontent.com/57390535/77340914-98196f80-6d4b-11ea-93ca-9d8a14c8b80d.png">
> 
> I think it's something related to `webbrowser`, which is the sub dependency of `rspotify`, the error message says `webbrowser` only supports Windows, Linux, Macos, BSD, it doesn't support your operating system, what kind of OS are you using ?

Mac OS

**Comment by ramsayleung** [comment]
It doesn't make sense, I use Mac OS either, I think the fail reason is that `webbroser` doesn't support `wasm`.

**Comment by hosseind2** [comment]
ok thanks for your help 👍
I will figure webbroser problem

**Comment by ramsayleung** [comment]
I am gonna close this issue, if you have any problem later, you could reopen it.
