### ISSUE TITLE
Podcast support

### ISSUE THREAD

**Issue by hrkfdn** [ramsayleung/rspotify#92]
Looks like there are now endpoints to search for podcasts and episodes:

https://developer.spotify.com/community/news/2020/03/20/introducing-podcasts-api/

**Comment by ramsayleung** [comment]
PR is welcome, or I could take time to implement the new endpoints.

**Comment by ramsayleung** [comment]
I am working on the new podcast endpoints, check this PR for more details:
https://github.com/ramsayleung/rspotify/pull/99

**Comment by hrkfdn** [comment]
> I am working on the new podcast endpoints, check this PR for more details:
> #99

So cool, thanks! I wanted to work on this myself and implemented parts of this, but ultimately didn't have the time to finish it. So thanks for putting in the effort.

**Comment by ramsayleung** [comment]
I just spent the whole weekend on working on this, the all new endpoints and examples of adding Podcast support has been added, the PR of adding Podcast support has been merged,  check the [CHANGELOG](https://github.com/ramsayleung/rspotify/blob/master/CHANGELOG.md) and [README](https://github.com/ramsayleung/rspotify/blob/master/README.md) for more change details, cheers. :)

**Comment by hrkfdn** [comment]
Awesome, thanks so much. With this I can implement podcast support in ncspot, which me and some other users will be very happy about. 🙇
